export default {

  workout: 'WORKOUT', 
  profile: 'Profile' ,
  edit_profile: 'View Profile ',
  feed: 'Request an Item',
  my_feed: 'MY Feed',
  FeedComments: 'all Comments',
  create_feed: 'create feed',
  EditFeed: 'edit feed',
  settings: 'Bid',
  notification: 'Notification',
  share_app: 'Share App',
  privacy_policy: 'Hire',
  term_condition: 'Find Business',
  delete_account: 'Delete Account',
  contact_us: 'Catalogues',
  logout: 'Logout',
  about_us: 'Specials Maps',
  my_workout: 'MY WORKOUT',
  comments: 'Comments',
  faq: 'Specials',
  change_password: 'Categories',
  // filter: 'Sort Order',
  near_by: 'Buy',

  my_Favirity:'My Favorites',
  my_Reviews:'My Reviews',
  rate_the_app:'Rate The Application',
  give_feedback:'Give Feedback',

  TRUE: true,
  FALSE: false,
  SUCCESS: true,
  ALREADY: 'already',
  LOGGEDIN: 'loggedIn',
  USERINFO: 'userinfo',
  addToCart: 'addToCart',
  FoodAPI: 'FoodAPI',
  WARNING: false,
  message: 'Something went wrong',
  FACEBOOK: 'facebook',
  user_like: 'true',
  user_unlike: 'false', 
};